package ir.hrka.download_manager.utilities

object Constants {

    const val TAG = "Download Manager"
    const val FOREGROUND_NOTIFICATION_CHANNEL_ID = "ir.hrka.download_manager_channel_foreground"
    const val DOWNLOAD_MANAGER_TAG = "DOWNLOAD_MANAGER_TAG"
    const val KEY_FILE_DOWNLOAD_RECEIVED_BYTES = "KEY_FILE_DOWNLOAD_RECEIVED_BYTES"
    const val KEY_FILE_DOWNLOAD_RATE = "KEY_FILE_DOWNLOAD_RATE"
    const val KEY_FILE_DOWNLOAD_REMAINING_MS = "KEY_FILE_DOWNLOAD_REMAINING_MS"
    const val KEY_DOWNLOADED_FILE_PATH = "KEY_DOWNLOADED_FILE_PATH"
    const val KEY_DOWNLOAD_FAILED_MESSAGE = "KEY_DOWNLOAD_FAILED_MESSAGE"
    const val KEY_RUN_IN_SERVICE = "KEY_IS_EXECUTED_IN_SERVICE"
    const val KEY_DOWNLOAD_LOCATION = "KEY_STORAGE_TYPE"
    const val KEY_FILE_CREATION_MODE = "KEY_WRITE_TYPE"
    const val KEY_FILE_URL = "KEY_FILE_URL"
    const val KEY_FILE_NAME = "KEY_FILE_NAME"
    const val KEY_FILE_SUFFIX = "KEY_FILE_SUFFIX"
    const val KEY_FILE_DIRECTORY_NAME = "KEY_FILE_DIRECTORY_NAME"
    const val KEY_FILE_VERSION_NAME = "KEY_FILE_VERSION_NAME"
    const val KEY_FILE_IS_ZIP = "KEY_FILE_IS_ZIP"
    const val KEY_FILE_UNZIPPED_DIRECTORY = "KEY_FILE_UNZIPPED_DIRECTORY"
    const val KEY_FILE_TOTAL_BYTES = "KEY_FILE_TOTAL_BYTES"
    const val KEY_FILE_ACCESS_TOKEN = "KEY_FILE_ACCESS_TOKEN"
}